// src/lib/strings.ts
// All UI text in Bangla — single source of truth
// RULE: Never hardcode UI strings in components.
// Always import and use from here.

export const strings = {
  appName: 'আইআরডি বাজেট ব্যবস্থাপনা',
  loading: 'লোড হচ্ছে...',
  saving: 'সংরক্ষণ হচ্ছে...',
  saved: 'সংরক্ষিত হয়েছে ✓',
  saveFailed: 'সংরক্ষণ ব্যর্থ হয়েছে',
  error: 'ত্রুটি',
  success: 'সফল',
  cancel: 'বাতিল',
  confirm: 'নিশ্চিত করুন',
  edit: 'সম্পাদনা',
  delete: 'মুছুন',
  back: 'পেছনে',
  next: 'পরবর্তী',
  previous: 'পূর্ববর্তী',
  close: 'বন্ধ করুন',
  total: 'মোট',
  grandTotal: 'সর্বমোট',
  taka: 'টাকা',

  yes: 'হ্যাঁ',
  no: 'না',
  search: 'অনুসন্ধান',
  select: 'নির্বাচন করুন',
  required: 'এই তথ্যটি আবশ্যক',
  optional: '(ঐচ্ছিক)',
  na: 'প্রযোজ্য নয়',

  landing: {
    title: 'বাজেট ম্যানেজমেন্ট সিস্টেম',
    subtitle: 'অভ্যন্তরীণ সম্পদ বিভাগ',
    enterBudgetId: 'আপনার অফিসের বাজেট আইডি লিখে সার্চ করুন',
    budgetIdPlaceholder: 'যেমন: 1110215102427',
    searchButton: 'সার্চ করুন',
    adminLogin: 'প্রশাসক লগইন',
    notFound: 'এই আইডিতে কোনো অফিস পাওয়া যায়নি।',
    registerPrompt: 'নতুন অফিস নিবন্ধন করতে নিচের বাটনে চাপুন।',
    registerButton: 'নতুন অফিস নিবন্ধন',
    foundOffice: 'এটা কি আপনার অফিস?',
    confirmOffice: 'হ্যাঁ, এটি আমার অফিস',
    wrongOffice: 'না, এটি আমার অফিস নয়',
    searchAgain: 'পুনরায় সার্চ',
    registerThis: 'অফিসটি নিবন্ধন করুন',
  },

  registration: {
    title: 'নতুন অফিস নিবন্ধন',
    officeName: 'অফিসের নাম',
    officeNamePlaceholder: 'যেমন: কর অঞ্চল-১১, ঢাকা',
    budgetId: 'বাজেট আইডি',
    budgetIdPlaceholder: 'যেমন: 1110215102427',
    department: 'বিভাগ',
    departmentPlaceholder: 'বিভাগ নির্বাচন করুন',
    parentOffice: 'উর্ধ্বতন অফিস',
    parentOfficePlaceholder: 'উর্ধ্বতন অফিস নির্বাচন করুন',
    officeType: 'অফিসের ধরন',
    officeTypePlaceholder: 'অফিসের ধরন নির্বাচন করুন',
    previewTitle: 'তথ্য পর্যালোচনা করুন',
    previewPrompt: 'নিচের তথ্যগুলো সঠিক কিনা যাচাই করুন',
    saveButton: 'নিবন্ধন সম্পন্ন করুন',
    editButton: 'সম্পাদনা করুন',
    successMessage: 'অফিস সফলভাবে নিবন্ধিত হয়েছে',
    alreadyExists: 'এই বাজেট আইডিতে ইতোমধ্যে একটি অফিস নিবন্ধিত আছে',
  },

  forms: {
    form1: { title: 'অফিসের মূল তথ্য', short: 'মূল তথ্য' },
    form2: { title: 'কর্মকর্তা ও কর্মচারীর বেতন তথ্য', short: 'বেতন তথ্য' },
    form3: { title: 'ভাতা সংক্রান্ত তথ্য', short: 'ভাতা' },
    form4: { title: 'ছুটি নগদায়ন ও বিনোদন ভাতা', short: 'ছুটি ও বিনোদন' },
    form5: { title: 'যানবাহন ও জ্বালানি তথ্য', short: 'যানবাহন' },
    form6: { title: 'যানবাহন ভাড়ার তথ্য', short: 'যানবাহন ভাড়া' },
    form7: { title: 'তথ্যপ্রযুক্তি সরঞ্জামের তথ্য', short: 'আইটি সরঞ্জাম' },
    form8: { title: 'ইউটিলিটি ব্যয়ের তথ্য', short: 'ইউটিলিটি' },
    form9: { title: 'অফিস ভাড়ার তথ্য', short: 'অফিস ভাড়া' },
    form10: { title: 'রিটার্ন সংক্রান্ত তথ্য', short: 'রিটার্ন তথ্য' },
  },

  form1: {
    headOfOffice: 'অফিস প্রধানের নাম',
    headOfOfficePlaceholder: 'যেমন: মোহাম্মদ আলী',
    designation: 'পদবি',
    designationPlaceholder: 'যেমন: কর কমিশনার',
    phone: 'ফোন নম্বর',
    phonePlaceholder: 'যেমন: ০১৭১১২৩৪৫৬৭',
    email: 'ইমেইল',
    emailPlaceholder: 'যেমন: office@nbr.gov.bd',
    address: 'অফিসের ঠিকানা',
    addressPlaceholder: 'সম্পূর্ণ ঠিকানা লিখুন',
  },

  form2: {
    title: 'গ্রেড অনুযায়ী কর্মকর্তা ও কর্মচারীর তথ্য',
    gradeColumn: 'গ্রেড',
    categoryColumn: 'শ্রেণি',
    countColumn: 'কর্মরত সংখ্যা',
    basicColumn: 'মোট মূল বেতন (মাসিক)',
    suspendedCountColumn: 'সাময়িক বরখাস্তকৃত সংখ্যা',
    suspendedBasicColumn: 'সাময়িক বরখাস্তদের মোট মূল বেতন',
    dueSalaryColumn: 'বকেয়া বেতনের পরিমাণ',
    suspendedDueColumn: 'সাময়িক বরখাস্তদের বকেয়া বেতন',
    totalRow: 'মোট',
    officerGrades: 'কর্মকর্তা (গ্রেড ১-৯)',
    staffGrades: 'কর্মচারী (গ্রেড ১০-২০)',
  },

  form3: {
    title: 'ভাতা সংক্রান্ত তথ্য',
    allowanceType: 'ভাতার ধরন',
    countLabel: 'সুবিধাভোগীর সংখ্যা',
    basicLabel: 'মোট মূল বেতন (মাসিক)',
    amountLabel: 'মোট পরিমাণ (টাকা)',
    dueLabel: 'বকেয়া (টাকা)',
    overtime: 'অধিকাল ভাতা (চালক)',
    duty: 'দায়িত্ব ভাতা',
    dress: 'পোশাক ভাতা',
    risk: 'ঝুঁকি ভাতা',
    hill: 'পাহাড়ী ভাতা',
    calculatedNote: 'স্বয়ংক্রিয়ভাবে গণনাকৃত',
    manualNote: 'সরাসরি পরিমাণ লিখুন',
  },

  form4: {
    leaveEncashmentTitle: 'ছুটি নগদায়ন',
    officerSection: 'কর্মকর্তা (গ্রেড ১-১০)',
    staffSection: 'কর্মচারী (গ্রেড ১১-২০)',
    basicLabel: 'মোট মূল বেতন (মাসিক)',
    dueLabel: 'বকেয়া (টাকা)',
    restRecreationTitle: 'শ্রান্তি ও বিনোদন ভাতা',
    restRecreationAmount: 'মোট পরিমাণ (টাকা)',
    restRecreationDue: 'বকেয়া (টাকা)',
    calculationNote: 'মোট মূল বেতন × ১২ মাস',
  },

  form5: {
    title: 'সরকারি যানবাহন ও জ্বালানি তথ্য',
    vehicleType: 'যানবাহনের ধরন',
    fuelType: 'জ্বালানির ধরন',
    countLabel: 'যানবাহনের সংখ্যা',
    maintenanceCost: 'রক্ষণাবেক্ষণ ব্যয় (বার্ষিক)',
    additionalExpense: 'অতিরিক্ত ব্যয় (টাকা)',
    addVehicle: '+ যানবাহন যোগ করুন',
    noVehicle: 'কোনো যানবাহন যোগ করা হয়নি',
  },

  form6: {
    title: 'ভাড়া করা যানবাহনের তথ্য',
    vehicleType: 'যানবাহনের ধরন',
    countLabel: 'ভাড়া করা যানবাহনের সংখ্যা',
    monthlyAllowance: 'মাসিক ভাড়া বরাদ্দ',
    calculationNote: 'মাসিক বরাদ্দ × সংখ্যা × ১২ মাস',
    addVehicle: '+ ভাড়ার যানবাহন যোগ করুন',
    noVehicle: 'কোনো ভাড়ার যানবাহন যোগ করা হয়নি',
  },

  form7: {
    inventoryTitle: 'বিদ্যমান আইটি সরঞ্জামের তথ্য',
    requirementTitle: 'আইটি সরঞ্জাম ক্রয়ের প্রয়োজনীয়তা',
    itemType: 'সরঞ্জামের ধরন',
    countLabel: 'বিদ্যমান সংখ্যা',
    damagedLabel: 'অকেজো সংখ্যা',
    tonerLabel: 'মাসিক টোনার মূল্য (টাকা)',
    requiredQty: 'প্রয়োজনীয় সংখ্যা',
    unitBudget: 'প্রতি ইউনিট বরাদ্দ',
    totalAmount: 'মোট পরিমাণ (টাকা)',
  },

  form8: {
    title: 'ইউটিলিটি ব্যয়ের তথ্য',
    utilityType: 'ইউটিলিটির ধরন',
    annualCost: 'বার্ষিক ব্যয় (টাকা)',
    due: 'বকেয়া (টাকা)',
    annualNote: 'সম্পূর্ণ বছরের পরিমাণ লিখুন',
  },

  form9: {
    title: 'অফিস ভবন ভাড়ার তথ্য',
    monthlyBill: 'মাসিক ভাড়া (সকল সম্পত্তি মিলিয়ে)',
    monthlyBillNote: 'গ্যারেজ ভাড়াসহ সকল ভাড়ার মোট পরিমাণ',
    vatNote: 'ভ্যাট স্বয়ংক্রিয়ভাবে যোগ হবে',
    vatAmount: 'ভ্যাট',
    due: 'বকেয়া ভাড়া (টাকা)',
    contractStart: 'চুক্তি শুরুর তারিখ',
    contractEnd: 'চুক্তি শেষের তারিখ',
    contractNote: 'তথ্যসূত্রের জন্য',
  },

  form10: {
    title: 'রিটার্ন সংক্রান্ত তথ্য',
    tinCount: 'মোট টিআইএন ধারকের সংখ্যা',
    tinCountPlaceholder: 'যেমন: ৫০০০',
    returnCount: 'দাখিলকৃত রিটার্নের সংখ্যা',
    returnCountPlaceholder: 'যেমন: ৩৫০০',
    postalExpense: 'গণনাকৃত ডাক ব্যয়',
    postalNote: 'দাখিলকৃত রিটার্ন × ডাক ব্যয় হার',
  },

  fields: {
    grade: 'গ্রেড',
    count: 'কর্মকর্তা/কর্মচারীর সংখ্যা',
    totalBasic: 'মূল বেতন',
    dueSalary: 'বকেয়া বেতন',
    suspendedCount: 'সাময়িক বরখাস্ত সংখ্যা',
    suspendedBasic: 'সাময়িক বরখাস্ত মূল বেতন',
    suspendedDue: 'সাময়িক বরখাস্ত বকেয়া',
  },

  budgetSheet: {
    title: 'বাজেট শিট',
    codeColumn: 'কোড',
    nameColumn: 'ব্যয় খাত',
    calculatedColumn: 'স্বয়ংক্রিয় (টাকা)',
    finalColumn: 'চূড়ান্ত বরাদ্দ (ম্যানুয়াল)',
    autoNote: 'ফর্মের তথ্য থেকে স্বয়ংক্রিয়ভাবে গণনাকৃত',
    totalRow: 'সর্বমোট',
    recalculateButton: 'পুনরায় গণনা করুন',
    recalculating: 'পুনরায় গণনা হচ্ছে...',
  },

  dashboard: {
    title: 'ড্যাশবোর্ড',
    welcome: 'স্বাগতম',
    formProgress: 'ফর্মের অগ্রগতি',
    viewBudgetSheet: 'বাজেট শিট দেখুন',
    statusDraft: 'খসড়া',
    statusSubmitted: 'দাখিলকৃত',
    formComplete: 'সম্পন্ন',
    formIncomplete: 'অসম্পন্ন',
    formNotStarted: 'শুরু হয়নি',
  },

  reports: {
    officeReport: 'অফিসের বাজেট প্রতিবেদন',
    groupReport: 'গ্রুপ একত্রিত প্রতিবেদন',
    codeWiseReport: 'কোড ভিত্তিক একত্রিত প্রতিবেদন',
  },

  admin: {
    dashboard: {
      title: 'প্রশাসক ড্যাশবোর্ড',
    },
  },

  login: {
    title: 'বাজেট অ্যাপ্লিকেশন',
    subtitle: 'লগইন করতে আপনার বাজেট কোড প্রদান করুন',
    budgetCode: 'বাজেট কোড (১৩ ডিজিট)',
    budgetCodePlaceholder: 'যেমন: ১২৩৪৫৬৭৮৯০১২৩',
    email: 'ইমেইল (প্রশাসক)',
    password: 'পাসওয়ার্ড',
    signIn: 'লগইন করুন',
    signingIn: 'লগইন হচ্ছে...',
    adminAccess: 'অ্যাডমিন প্যানেল',
  },

  errors: {
    general: 'একটি ত্রুটি হয়েছে। পুনরায় চেষ্টা করুন।',
    network: 'ইন্টারনেট সংযোগ সমস্যা। পুনরায় চেষ্টা করুন।',
    notFound: 'তথ্য পাওয়া যায়নি।',
    unauthorized: 'আপনার এই তথ্য দেখার অনুমতি নেই।',
    loadFailed: 'তথ্য লোড করতে সমস্যা হয়েছে।',
  },
} as const;
